name = "bible-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Keep workers.dev subdomain active as backup
workers_dev = true

routes = [
  { pattern = "bible-api.dws-cloud.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "bible-db"
database_id = "2ca76e47-a8ac-4762-960f-948456903507"
